#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------
# markdown: redcarpet-pygments

# Which carpentry is this ("swc", "dc", "lc", or "cp")?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor traning for instance)
carpentry: "swc"

# Overall title for pages.
title: "COMP125 Lecture Notes"


#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "lesson"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Email address, no mailto:
email: "gaurav.gupta@mq.edu.au"

# Sites.
amy_site: "https://amy.software-carpentry.org/workshops"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "http://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
lc_site: "https://librarycarpentry.github.io/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"

# Surveys.
pre_survey: "https://www.surveymonkey.com/r/swc_pre_workshop_v1?workshop_id="
post_survey: "https://www.surveymonkey.com/r/swc_post_workshop_v1?workshop_id="
training_post_survey: "https://www.surveymonkey.com/r/post-instructor-training"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0


collections_dir: _collections

# Specify that things in the episodes collection should be output.
collections:
    episodes:
        output: true
        permalink: /:collection/:path
    extras:
        output: true
        permalink: /:path/index.html
    01-introduction:
        output: true
        permalink: /:collection/:path
    02-static-debugging-unit-testing:
        output: true
        permalink: /:collection/:path
    03-classes-and-objects:
        output: true
        permalink: /:collection/:path
    04-searching-and-sorting:
        output: true
        permalink: /:collection/:path
    05-recursion:
        output: true
        permalink: /:collection/:path
    06-lists:
        output: true
        permalink: /:collection/:path
# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page
  - scope:
      path: ""
      type: 01-introduction
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: 02-static-debugging-unit-testing
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: 03-classes-and-objects
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: 04-searching-and-sorting
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: 05-recursion
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: 06-lists
    values:
      root: ..
      layout: episode
  # - scope:
  #     path: "_collections/*/99-aio.md"
  #   values:
  #     collection_all_in_one: true

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - makeNavigationList.py
  - portingToMarkdown/
  - workshops/
  - archive/
  - workHours.csv
  - imageMagick.md
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
# Turn on built-in syntax highlighting.
highlighter: rouge

markdown: kramdown


# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
